global:
  n_observations: 500
variables:
  outcome:
    mean: 100
    std: 5
  random:
    type: 'numeric'
    n: 20
    std:
      multiplier: 5
    mean:
      multiplier: 5
    max_order: 3
  related:
    type: 'numeric'
    n: 5
    std:
      multiplier: 5
    mean:
      multiplier: 5
    additive_column: 'outcome'
    max_order: 3
  correlated:
    type: 'numeric'
    n: 0
    std:
      multiplier: 1
    mean:
      multiplier: 0
    additive_column: 'related_0'
